name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - develop  # 或者你使用的是 master 分支

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # 指定 Node.js 版本

    - name: Install Dependencies
      run: npm install

    - name: Build and Export Next.js App
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: develop  # GitHub Pages 分支
        folder: out       # Next.js 导出的静态文件目录